apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka101
  name: kafka101
  namespace: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  selector:
    app: kafka101
status:
  loadBalancer: {}
