apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zk1
  name: zk1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk1
  template:
    metadata:
      labels:
        app: zk1
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:7.1.0
          name: zookeeper1
          ports:
            - containerPort: 2181
          resources: {}
      restartPolicy: Always
status: {}
