apiVersion: v1
kind: Service
metadata:
  labels:
    app: zk1
  name: zookeeper1
  namespace: kafka
spec:
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: 2181
  selector:
    app: zk1
status:
  loadBalancer: {}
